updated semester delete
cepdnaclk/portal.ce.pdn.ac.lk pull request #116
Opened 2024-09-15 10:29 UTC by supundulara

2024-09-15 11:04 UTC, NuwanJ requested changes
Can you do the same check on the `destroy` method and throw an error?

2024-09-21 12:19 UTC, NuwanJ commented on app/Http/Controllers/Backend/SemesterController.php
> +                ->withErrors('Cannot delete semester as it has associated courses. Please reassign or delete these courses first.');
Can you update the error message as 

```
Can not delete the semester as it already has associated courses. Please reassign or delete those courses first.
```

2024-09-21 15:48 UTC, supundulara commented on app/Http/Controllers/Backend/SemesterController.php
> +                ->withErrors('Cannot delete semester as it has associated courses. Please reassign or delete these courses first.');
sure aiya

2024-09-21 17:51 UTC, NuwanJ approved these changes

2024-09-21 17:51 UTC, merged