unit tests for semesters
cepdnaclk/portal.ce.pdn.ac.lk pull request #117
Opened 2024-09-15 10:55 UTC by supundulara

2024-09-15 11:06 UTC, NuwanJ requested changes

2024-09-15 11:06 UTC, NuwanJ commented on tests/Feature/Backend/Semesters/SemesterTest.php
Can you add some unit tests to check the uniqueness of the semester `url`, and the correctness of the `academic_program` as well?

2024-09-16 18:48 UTC, supundulara commented on tests/Feature/Backend/Semesters/SemesterTest.php
Sure aiya, I'll add them.

2024-09-21 17:48 UTC, NuwanJ approved these changes

2024-09-21 17:48 UTC, merged