163 cr adding a new field into events table 2
cepdnaclk/portal.ce.pdn.ac.lk pull request #166
Opened 2024-10-09 07:46 UTC by IsharaEkanayaka

2024-10-09 08:14 UTC, NuwanJ requested changes

2024-10-09 08:14 UTC, NuwanJ commented on resources/views/backend/event/create.blade.php
> +
Can you try something like this? It is simple and robust

https://dev.to/snehalkadwe/how-to-use-select-2-with-multiple-options-in-laravel-and-livewire-4p4a (Hope you can do alphine)

Or you can reuse the item adder with some small changes.

2024-10-09 09:51 UTC, IsharaEkanayaka commented on app/Http/Controllers/Backend/EventController.php
> +            $events = Event::all();
it is not needed. removed it

2024-10-09 09:54 UTC, IsharaEkanayaka commented on app/Http/Controllers/Backend/EventController.php
> +            $eventTypes = $event->event_type;
thanks for pointing. It is not used anywhere

2024-10-11 02:53 UTC, NuwanJ approved these changes
Approved with minor UI changes

2024-10-11 02:54 UTC, merged