seed semester and course data
cepdnaclk/portal.ce.pdn.ac.lk pull request #95
Opened 2024-09-09 11:49 UTC by supundulara

2024-09-09 14:56 UTC, NuwanJ commented on database/seeders/DatabaseSeeder.php
> +        if (App::environment('local')) {
Can you include the followings as well under if condition? Thanks !

$this->call(NewsSeeder::class);
$this->call(EventSeeder::class);

2024-09-09 14:58 UTC, NuwanJ requested changes
Can you resolve the comments? Thanks

2024-09-09 15:44 UTC, supundulara commented
> Can you resolve the comments? Thanks

ok aiya

2024-09-10 09:37 UTC, NuwanJ approved these changes

2024-09-10 09:37 UTC, merged